# Generated by Django 4.0.6 on 2022-07-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('email', models.EmailField(help_text='Deve terminar com @dominio.com', max_length=100, verbose_name='E-mail')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('seniority', models.CharField(choices=[('JR', 'Junior'), ('PL', 'Pleno'), ('SR', 'Senior')], max_length=10, verbose_name='Senioridade')),
            ],
            options={
                'verbose_name': 'Programador',
                'verbose_name_plural': 'Programadores',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
