# Generated by Django 4.2.14 on 2024-07-11 02:28

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
